package sv.edu.udb.www.Cuponeria.entities;
// Generated 11-23-2018 05:14:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="lacuponera"
    , uniqueConstraints = @UniqueConstraint(columnNames="Direccion") 
)
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private String telefono;
     private String direccion;
     private String dui;
     private boolean verificado;
     private String token;
     private Set<Cupones> cuponeses = new HashSet<Cupones>(0);

    public Cliente() {
    }

	
    public Cliente(String nombre, String apellido, String telefono, String direccion, String dui, boolean verificado, String token) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.direccion = direccion;
        this.dui = dui;
        this.verificado = verificado;
        this.token = token;
    }
    public Cliente(String nombre, String apellido, String telefono, String direccion, String dui, boolean verificado, String token, Set<Cupones> cuponeses) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.direccion = direccion;
       this.dui = dui;
       this.verificado = verificado;
       this.token = token;
       this.cuponeses = cuponeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Nombre", nullable=false, length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false, length=150)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="Telefono", nullable=false, length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Direccion", unique=true, nullable=false, length=150)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="DUI", nullable=false, length=10)
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }

    
    @Column(name="Verificado", nullable=false)
    public boolean isVerificado() {
        return this.verificado;
    }
    
    public void setVerificado(boolean verificado) {
        this.verificado = verificado;
    }

    
    @Column(name="Token", nullable=false, length=250)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Cupones> getCuponeses() {
        return this.cuponeses;
    }
    
    public void setCuponeses(Set<Cupones> cuponeses) {
        this.cuponeses = cuponeses;
    }




}


