package sv.edu.udb.www.Cuponeria.entities;
// Generated 11-23-2018 05:14:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cupones generated by hbm2java
 */
@Entity
@Table(name="cupones"
    ,catalog="lacuponera"
)
public class Cupones  implements java.io.Serializable {


     private String id;
     private Cliente cliente;
     private EstadoCupon estadoCupon;
     private Promocion promocion;
     private Date fechaCanje;
     private Date fechaCompra;

    public Cupones() {
    }

    public Cupones(String id, Cliente cliente, EstadoCupon estadoCupon, Promocion promocion, Date fechaCanje, Date fechaCompra) {
       this.id = id;
       this.cliente = cliente;
       this.estadoCupon = estadoCupon;
       this.promocion = promocion;
       this.fechaCanje = fechaCanje;
       this.fechaCompra = fechaCompra;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false, length=13)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_estado", nullable=false)
    public EstadoCupon getEstadoCupon() {
        return this.estadoCupon;
    }
    
    public void setEstadoCupon(EstadoCupon estadoCupon) {
        this.estadoCupon = estadoCupon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_promocion", nullable=false)
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_canje", nullable=false, length=10)
    public Date getFechaCanje() {
        return this.fechaCanje;
    }
    
    public void setFechaCanje(Date fechaCanje) {
        this.fechaCanje = fechaCanje;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_compra", nullable=false, length=10)
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }




}


