package sv.edu.udb.www.Cuponeria.entities;
// Generated 11-23-2018 08:10:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cupones generated by hbm2java
 */
@Entity
@Table(name="cupones"
    ,catalog="lacuponera"
)
public class Cupones  implements java.io.Serializable {


     private String codigoCupon;
     private Clientes clientes;
     private Promocion promocion;
     private Date fechaCompra;
     private Date fechaCambio;
     private int estado;
     private boolean confirmado;

    public Cupones() {
    }

    public Cupones(String codigoCupon, Clientes clientes, Promocion promocion, Date fechaCompra, Date fechaCambio, int estado, boolean confirmado) {
       this.codigoCupon = codigoCupon;
       this.clientes = clientes;
       this.promocion = promocion;
       this.fechaCompra = fechaCompra;
       this.fechaCambio = fechaCambio;
       this.estado = estado;
       this.confirmado = confirmado;
    }
   
     @Id 

    
    @Column(name="codigo_cupon", unique=true, nullable=false, length=13)
    public String getCodigoCupon() {
        return this.codigoCupon;
    }
    
    public void setCodigoCupon(String codigoCupon) {
        this.codigoCupon = codigoCupon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_cliente", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_promocion", nullable=false)
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_compra", nullable=false, length=10)
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_cambio", nullable=false, length=10)
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

    
    @Column(name="confirmado", nullable=false)
    public boolean isConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }




}


