package sv.edu.udb.www.Cuponeria.entities;
// Generated 11-23-2018 08:10:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Empleados generated by hbm2java
 */
@Entity
@Table(name="empleados"
    ,catalog="lacuponera"
)
public class Empleados  implements java.io.Serializable {


     private Integer codigoEmpleado;
     private Empresas empresas;
     private Usuarios usuarios;
     private String nombres;
     private String apellidos;
     private boolean confirmado;

    public Empleados() {
    }

    public Empleados(Empresas empresas, Usuarios usuarios, String nombres, String apellidos, boolean confirmado) {
       this.empresas = empresas;
       this.usuarios = usuarios;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.confirmado = confirmado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codigo_empleado", unique=true, nullable=false)
    public Integer getCodigoEmpleado() {
        return this.codigoEmpleado;
    }
    
    public void setCodigoEmpleado(Integer codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_empresa", nullable=false)
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="nombres", nullable=false, length=100)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="confirmado", nullable=false)
    public boolean isConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }




}


