package sv.edu.udb.www.Cuponeria.entities;
// Generated 11-23-2018 05:14:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,catalog="lacuponera"
)
public class Empresa  implements java.io.Serializable {


     private Integer id;
     private Rubro rubro;
     private String identificador;
     private String nombre;
     private String direccion;
     private String nombreContacto;
     private String telefono;
     private long porcentajeComicion;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Promocion> promocions = new HashSet<Promocion>(0);

    public Empresa() {
    }

	
    public Empresa(Rubro rubro, String identificador, String nombre, String direccion, String nombreContacto, String telefono, long porcentajeComicion) {
        this.rubro = rubro;
        this.identificador = identificador;
        this.nombre = nombre;
        this.direccion = direccion;
        this.nombreContacto = nombreContacto;
        this.telefono = telefono;
        this.porcentajeComicion = porcentajeComicion;
    }
    public Empresa(Rubro rubro, String identificador, String nombre, String direccion, String nombreContacto, String telefono, long porcentajeComicion, Set<Usuario> usuarios, Set<Promocion> promocions) {
       this.rubro = rubro;
       this.identificador = identificador;
       this.nombre = nombre;
       this.direccion = direccion;
       this.nombreContacto = nombreContacto;
       this.telefono = telefono;
       this.porcentajeComicion = porcentajeComicion;
       this.usuarios = usuarios;
       this.promocions = promocions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_rubro", nullable=false)
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }

    
    @Column(name="identificador", nullable=false, length=6)
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    
    @Column(name="Nombre", nullable=false, length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Direccion", nullable=false, length=150)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Nombre_contacto", nullable=false, length=100)
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }

    
    @Column(name="Telefono", nullable=false, length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Porcentaje_comicion", nullable=false, precision=10, scale=0)
    public long getPorcentajeComicion() {
        return this.porcentajeComicion;
    }
    
    public void setPorcentajeComicion(long porcentajeComicion) {
        this.porcentajeComicion = porcentajeComicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Promocion> getPromocions() {
        return this.promocions;
    }
    
    public void setPromocions(Set<Promocion> promocions) {
        this.promocions = promocions;
    }




}


