package sv.edu.udb.www.Cuponeria.entities;
// Generated 11-23-2018 08:10:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Empresas generated by hbm2java
 */
@Entity
@Table(name="empresas"
    ,catalog="lacuponera"
    , uniqueConstraints = @UniqueConstraint(columnNames="codigo_empresa") 
)
public class Empresas  implements java.io.Serializable {


     private Integer idEmpresa;
     private Rubros rubros;
     private Usuarios usuarios;
     private String nombreEmpresa;
     private String codigoEmpresa;
     private String direccion;
     private String nombreContacto;
     private String telefono;
     private long comision;
     private boolean confirmado;
     private Set<Promocion> promocions = new HashSet<Promocion>(0);
     private Set<Empleados> empleadoses = new HashSet<Empleados>(0);

    public Empresas() {
    }

	
    public Empresas(Rubros rubros, Usuarios usuarios, String nombreEmpresa, String codigoEmpresa, String direccion, String nombreContacto, String telefono, long comision, boolean confirmado) {
        this.rubros = rubros;
        this.usuarios = usuarios;
        this.nombreEmpresa = nombreEmpresa;
        this.codigoEmpresa = codigoEmpresa;
        this.direccion = direccion;
        this.nombreContacto = nombreContacto;
        this.telefono = telefono;
        this.comision = comision;
        this.confirmado = confirmado;
    }
    public Empresas(Rubros rubros, Usuarios usuarios, String nombreEmpresa, String codigoEmpresa, String direccion, String nombreContacto, String telefono, long comision, boolean confirmado, Set<Promocion> promocions, Set<Empleados> empleadoses) {
       this.rubros = rubros;
       this.usuarios = usuarios;
       this.nombreEmpresa = nombreEmpresa;
       this.codigoEmpresa = codigoEmpresa;
       this.direccion = direccion;
       this.nombreContacto = nombreContacto;
       this.telefono = telefono;
       this.comision = comision;
       this.confirmado = confirmado;
       this.promocions = promocions;
       this.empleadoses = empleadoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_empresa", unique=true, nullable=false)
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rubro", nullable=false)
    public Rubros getRubros() {
        return this.rubros;
    }
    
    public void setRubros(Rubros rubros) {
        this.rubros = rubros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="nombre_empresa", nullable=false, length=100)
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }

    
    @Column(name="codigo_empresa", unique=true, nullable=false, length=6)
    public String getCodigoEmpresa() {
        return this.codigoEmpresa;
    }
    
    public void setCodigoEmpresa(String codigoEmpresa) {
        this.codigoEmpresa = codigoEmpresa;
    }

    
    @Column(name="direccion", nullable=false, length=200)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="nombre_contacto", nullable=false, length=60)
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }

    
    @Column(name="telefono", nullable=false, length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="comision", nullable=false, precision=10, scale=0)
    public long getComision() {
        return this.comision;
    }
    
    public void setComision(long comision) {
        this.comision = comision;
    }

    
    @Column(name="confirmado", nullable=false)
    public boolean isConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresas")
    public Set<Promocion> getPromocions() {
        return this.promocions;
    }
    
    public void setPromocions(Set<Promocion> promocions) {
        this.promocions = promocions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresas")
    public Set<Empleados> getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set<Empleados> empleadoses) {
        this.empleadoses = empleadoses;
    }




}


