package sv.edu.udb.www.Cuponeria.entities;
// Generated 11-23-2018 05:14:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promocion generated by hbm2java
 */
@Entity
@Table(name="promocion"
    ,catalog="lacuponera"
)
public class Promocion  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private EstadoOferta estadoOferta;
     private String titulo;
     private long precioRegular;
     private long precioOferta;
     private int cuponesDisponibles;
     private Date fechaInicio;
     private Date fechaLimite;
     private String descripcionOferta;
     private Date fechaLimiteUso;
     private String img;
     private Set<Cupones> cuponeses = new HashSet<Cupones>(0);

    public Promocion() {
    }

	
    public Promocion(Empresa empresa, EstadoOferta estadoOferta, String titulo, long precioRegular, long precioOferta, int cuponesDisponibles, Date fechaInicio, Date fechaLimite, String descripcionOferta, Date fechaLimiteUso, String img) {
        this.empresa = empresa;
        this.estadoOferta = estadoOferta;
        this.titulo = titulo;
        this.precioRegular = precioRegular;
        this.precioOferta = precioOferta;
        this.cuponesDisponibles = cuponesDisponibles;
        this.fechaInicio = fechaInicio;
        this.fechaLimite = fechaLimite;
        this.descripcionOferta = descripcionOferta;
        this.fechaLimiteUso = fechaLimiteUso;
        this.img = img;
    }
    public Promocion(Empresa empresa, EstadoOferta estadoOferta, String titulo, long precioRegular, long precioOferta, int cuponesDisponibles, Date fechaInicio, Date fechaLimite, String descripcionOferta, Date fechaLimiteUso, String img, Set<Cupones> cuponeses) {
       this.empresa = empresa;
       this.estadoOferta = estadoOferta;
       this.titulo = titulo;
       this.precioRegular = precioRegular;
       this.precioOferta = precioOferta;
       this.cuponesDisponibles = cuponesDisponibles;
       this.fechaInicio = fechaInicio;
       this.fechaLimite = fechaLimite;
       this.descripcionOferta = descripcionOferta;
       this.fechaLimiteUso = fechaLimiteUso;
       this.img = img;
       this.cuponeses = cuponeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_empresa", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_estado", nullable=false)
    public EstadoOferta getEstadoOferta() {
        return this.estadoOferta;
    }
    
    public void setEstadoOferta(EstadoOferta estadoOferta) {
        this.estadoOferta = estadoOferta;
    }

    
    @Column(name="Titulo", nullable=false, length=225)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="Precio_regular", nullable=false, precision=10, scale=0)
    public long getPrecioRegular() {
        return this.precioRegular;
    }
    
    public void setPrecioRegular(long precioRegular) {
        this.precioRegular = precioRegular;
    }

    
    @Column(name="Precio_oferta", nullable=false, precision=10, scale=0)
    public long getPrecioOferta() {
        return this.precioOferta;
    }
    
    public void setPrecioOferta(long precioOferta) {
        this.precioOferta = precioOferta;
    }

    
    @Column(name="Cupones_disponibles", nullable=false)
    public int getCuponesDisponibles() {
        return this.cuponesDisponibles;
    }
    
    public void setCuponesDisponibles(int cuponesDisponibles) {
        this.cuponesDisponibles = cuponesDisponibles;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_inicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_limite", nullable=false, length=10)
    public Date getFechaLimite() {
        return this.fechaLimite;
    }
    
    public void setFechaLimite(Date fechaLimite) {
        this.fechaLimite = fechaLimite;
    }

    
    @Column(name="Descripcion_oferta", nullable=false, length=150)
    public String getDescripcionOferta() {
        return this.descripcionOferta;
    }
    
    public void setDescripcionOferta(String descripcionOferta) {
        this.descripcionOferta = descripcionOferta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_limite_uso", nullable=false, length=10)
    public Date getFechaLimiteUso() {
        return this.fechaLimiteUso;
    }
    
    public void setFechaLimiteUso(Date fechaLimiteUso) {
        this.fechaLimiteUso = fechaLimiteUso;
    }

    
    @Column(name="Img", nullable=false, length=225)
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="promocion")
    public Set<Cupones> getCuponeses() {
        return this.cuponeses;
    }
    
    public void setCuponeses(Set<Cupones> cuponeses) {
        this.cuponeses = cuponeses;
    }




}


