package sv.edu.udb.www.Cuponeria.entities;
// Generated 11-23-2018 08:10:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rubros generated by hbm2java
 */
@Entity
@Table(name="rubros"
    ,catalog="lacuponera"
)
public class Rubros  implements java.io.Serializable {


     private Integer idRubro;
     private String rubro;
     private String descripcion;
     private Set<Empresas> empresases = new HashSet<Empresas>(0);

    public Rubros() {
    }

	
    public Rubros(String rubro, String descripcion) {
        this.rubro = rubro;
        this.descripcion = descripcion;
    }
    public Rubros(String rubro, String descripcion, Set<Empresas> empresases) {
       this.rubro = rubro;
       this.descripcion = descripcion;
       this.empresases = empresases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_rubro", unique=true, nullable=false)
    public Integer getIdRubro() {
        return this.idRubro;
    }
    
    public void setIdRubro(Integer idRubro) {
        this.idRubro = idRubro;
    }

    
    @Column(name="rubro", nullable=false, length=50)
    public String getRubro() {
        return this.rubro;
    }
    
    public void setRubro(String rubro) {
        this.rubro = rubro;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rubros")
    public Set<Empresas> getEmpresases() {
        return this.empresases;
    }
    
    public void setEmpresases(Set<Empresas> empresases) {
        this.empresases = empresases;
    }




}


